import { CropKey } from '@/types/map';
import { Wheat, Leaf, Sprout, Carrot, Layers } from 'lucide-react';
import React from 'react';

export const cropColors: Record<CropKey, string> = {
  rice: '#34d399',
  sugarcane: '#a3e635',
  cassava: '#f59e0b',
  rubber: '#10b981',
  corn: '#f97316',
  mixed: '#94a3b8',
};

export const cropIcon: Record<CropKey, React.ComponentType<{ className?: string }>> = {
  rice: Wheat,
  sugarcane: Sprout,
  cassava: Carrot,
  rubber: Leaf,
  corn: Wheat,
  mixed: Layers,
};

export const provinceDominantCrop: Record<string, CropKey> = {
  'กรุงเทพมหานคร': 'mixed',
  'พระนครศรีอยุธยา': 'rice',
  'อ่างทอง': 'rice',
  'สิงห์บุรี': 'rice',
  'ลพบุรี': 'sugarcane',
  'สระบุรี': 'sugarcane',
  'ปทุมธานี': 'rice',
  'นนทบุรี': 'mixed',
  'นครปฐม': 'rice',
  'สมุทรสาคร': 'mixed',
  'สมุทรปราการ': 'mixed',
  'สมุทรสงคราม': 'mixed',
  'ราชบุรี': 'sugarcane',
  'กาญจนบุรี': 'sugarcane',
  'สุพรรณบุรี': 'rice',
  'เพชรบุรี': 'mixed',
  'ประจวบคีรีขันธ์': 'mixed',
  'นครสวรรค์': 'rice',
  'อุทัยธานี': 'rice',
  'ชัยนาท': 'rice',
  'กำแพงเพชร': 'cassava',
  'พิษณุโลก': 'rice',
  'พิจิตร': 'rice',
  'สุโขทัย': 'rice',
  'ตาก': 'mixed',
  'เพชรบูรณ์': 'corn',
  'อุตรดิตถ์': 'rice',
  'แพร่': 'rice',
  'น่าน': 'rice',
  'พะเยา': 'rice',
  'เชียงราย': 'rice',
  'เชียงใหม่': 'rice',
  'ลำปาง': 'corn',
  'ลำพูน': 'corn',
  'แม่ฮ่องสอน': 'mixed',
  'เลย': 'corn',
  'นครราชสีมา': 'cassava',
  'บุรีรัมย์': 'cassava',
  'สุรินทร์': 'cassava',
  'ศรีสะเกษ': 'cassava',
  'อุบลราชธานี': 'cassava',
  'ยโสธร': 'rice',
  'ร้อยเอ็ด': 'rice',
  'มหาสารคาม': 'rice',
  'ขอนแก่น': 'cassava',
  'ชัยภูมิ': 'cassava',
  'กาฬสินธุ์': 'rice',
  'สกลนคร': 'rice',
  'นครพนม': 'rice',
  'มุกดาหาร': 'cassava',
  'บึงกาฬ': 'cassava',
  'หนองบัวลำภู': 'cassava',
  'หนองคาย': 'rice',
  'อุดรธานี': 'cassava',
  'อำนาจเจริญ': 'rice',
  'ชลบุรี': 'mixed',
  'ระยอง': 'mixed',
  'จันทบุรี': 'mixed',
  'ตราด': 'mixed',
  'ฉะเชิงเทรา': 'rice',
  'ปราจีนบุรี': 'cassava',
  'สระแก้ว': 'cassava',
  'ชุมพร': 'rubber',
  'ระนอง': 'rubber',
  'สุราษฎร์ธานี': 'rubber',
  'นครศรีธรรมราช': 'rubber',
  'พัทลุง': 'rubber',
  'สงขลา': 'rubber',
  'สตูล': 'rubber',
  'ตรัง': 'rubber',
  'กระบี่': 'rubber',
  'พังงา': 'rubber',
  'ภูเก็ต': 'mixed',
  'ยะลา': 'rubber',
  'นราธิวาส': 'rubber',
  'ปัตตานี': 'rubber',
  'อยุธยา': 'rice',
};

export const UI_CONSTANTS = {
  tooltipOffset: { x: 12, y: 12 },
  selected: { translateY: -4, scale: 1.05, shadow: '0 8px 12px rgba(0,0,0,0.25)' },
  dimOpacity: 0.35,
} as const;


